<Project>
  <Target Name="PackLocalAfterSolutionBuild" AfterTargets="Build" Condition="'$(BuildingSolutionFile)' == 'true' and '$(SkipPackLocal)' != 'true' and '$(SolutionFileName)' == 'Fmacias.TplQueue.Abstractions.sln' and '$(MSBuildProjectName)' == 'Fmacias.TplQueue.Abstractions'">
    <Exec Command="powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(SolutionDir)pack-local.ps1&quot;" WorkingDirectory="$(SolutionDir)" />
  </Target>
</Project>
